# Generated by Django 4.2.27 on 2025-12-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_pipelinerun_pipelinestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_steps', to='agents.agentrun'),
        ),
    ]
