# Generated by Django 4.2.27 on 2026-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_pipelinestep_agent_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='agents.pipelinestep'),
        ),
    ]
