# Generated by Django 4.2.27 on 2026-01-12 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
        ('agents', '0004_pipelinestep_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='agents.pipelinerun')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='transcripts.transcript')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterpretationSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('corrected_text', models.TextField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField()),
                ('categories', models.JSONField(blank=True, default=list)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='agents.interpretationrun')),
            ],
            options={
                'ordering': ['run', 'order_index'],
            },
        ),
    ]
