# Generated by Django 4.2.27 on 2026-01-14 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_interpretationrun_corrected_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plane_id', models.UUIDField(db_index=True, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plane_id', models.UUIDField(db_index=True, unique=True)),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plane_id', models.UUIDField(db_index=True, unique=True)),
                ('sequence_id', models.IntegerField()),
                ('plane_key', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('state_id', models.UUIDField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, default='', max_length=64)),
                ('priority', models.CharField(blank=True, default='none', max_length=32)),
                ('description_text', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.syncedmodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.syncedproject')),
            ],
            options={
                'ordering': ['project', 'sequence_id'],
            },
        ),
        migrations.AddIndex(
            model_name='syncedproject',
            index=models.Index(fields=['plane_id'], name='agents_sync_plane_i_27ca5a_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedproject',
            index=models.Index(fields=['identifier'], name='agents_sync_identif_28a44d_idx'),
        ),
        migrations.AddField(
            model_name='syncedmodule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='agents.syncedproject'),
        ),
        migrations.AddIndex(
            model_name='syncedtask',
            index=models.Index(fields=['plane_id'], name='agents_sync_plane_i_ed53f7_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedtask',
            index=models.Index(fields=['plane_key'], name='agents_sync_plane_k_383f14_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedtask',
            index=models.Index(fields=['project', 'state_name'], name='agents_sync_project_d6cce1_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedtask',
            index=models.Index(fields=['sequence_id'], name='agents_sync_sequenc_43fb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='syncedmodule',
            index=models.Index(fields=['plane_id'], name='agents_sync_plane_i_880166_idx'),
        ),
    ]
