# Generated by Django 4.2.27 on 2026-01-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_syncedmodule_syncedproject_syncedtask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncedtask',
            name='module',
        ),
        migrations.RemoveField(
            model_name='syncedtask',
            name='project',
        ),
        migrations.DeleteModel(
            name='SyncedModule',
        ),
        migrations.DeleteModel(
            name='SyncedProject',
        ),
        migrations.DeleteModel(
            name='SyncedTask',
        ),
    ]
