# Generated by Django 4.2.27 on 2026-01-29 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
        ('agents', '0008_remove_syncedtask_module_remove_syncedtask_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_id', models.UUIDField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('context_summary', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_projects', to='transcripts.transcript')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='agents_prop_status_19cea9_idx'), models.Index(fields=['transcript'], name='agents_prop_transcr_572cae_idx'), models.Index(fields=['created_at'], name='agents_prop_created_d58956_idx')],
            },
        ),
    ]
