# Generated by Django 4.2.27 on 2026-01-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane_agent', '0001_initial'),
        ('agents', '0011_remove_proposedmodule_context_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposedmodule',
            old_name='module_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='proposedmodule',
            name='project_name',
        ),
        migrations.AddField(
            model_name='proposedmodule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_modules', to='plane_agent.syncedproject'),
        ),
    ]
