# Generated by Django 4.2.27 on 2026-01-30 09:51

from django.db import migrations, models
import django.db.models.deletion
from django.apps import apps


class Migration(migrations.Migration):

    dependencies = [('agents', '0011_remove_proposedmodule_context_summary_and_more')]
    if any(config.label == 'plane_agent' for config in apps.get_app_configs()):
        dependencies.insert(0, ('plane_agent', '0001_initial'))

    operations = [
        migrations.RenameField(
            model_name='proposedmodule',
            old_name='module_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='proposedmodule',
            name='project_name',
        ),
        migrations.AddField(
            model_name='proposedmodule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_modules', to='plane_agent.syncedproject'),
        ),
    ]
