# Generated by Django 4.2.27 on 2026-01-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_rename_module_name_proposedmodule_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposedModule',
        ),
    ]
