# Generated by Django 4.2.27 on 2026-01-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_delete_proposedmodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposedProject',
        ),
    ]
