# Generated by Django 4.2.27 on 2026-02-10 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0001_initial"),
        ("agents", "0016_remove_proposed_project"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="InterpretationSegment"),
                migrations.DeleteModel(name="InterpretationRun"),
            ],
        ),
    ]

