# Generated by Django 4.2.27 on 2026-01-29 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.apps import apps


class Migration(migrations.Migration):

    dependencies = [('agents', '0009_proposedproject')]
    if any(config.label == 'transcripts' for config in apps.get_app_configs()):
        dependencies.insert(0, ('transcripts', '0001_initial'))

    operations = [
        migrations.CreateModel(
            name='ProposedModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_id', models.UUIDField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('module_name', models.CharField(max_length=255)),
                ('context_summary', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_modules', to='transcripts.transcript')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='agents_prop_status_879cd2_idx'), models.Index(fields=['transcript'], name='agents_prop_transcr_1194ed_idx'), models.Index(fields=['created_at'], name='agents_prop_created_f6835f_idx')],
            },
        ),
    ]
