# Generated by Django 4.2.27 on 2026-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_proposedmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedmodule',
            name='context_summary',
        ),
        migrations.AddField(
            model_name='proposedmodule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposedmodule',
            name='project_name',
            field=models.CharField(default='', help_text='Target project name inferred from content', max_length=255),
            preserve_default=False,
        ),
    ]
