# Generated by Django 4.2.27 on 2026-02-10 00:00

from django.db import migrations
from django.apps import apps


class Migration(migrations.Migration):
    dependencies = [("agents", "0016_remove_proposed_project")]
    if any(config.label == "personal" for config in apps.get_app_configs()):
        dependencies.insert(0, ("personal", "0001_initial"))

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="InterpretationSegment"),
                migrations.DeleteModel(name="InterpretationRun"),
            ],
        ),
    ]
